import { Racket } from "./racket";

export const RACKETS: Racket[] = [
    {
        id: 1,
        name: "Astrox 88D Pro",
        price: 264.99,
        length: 675,
        balancePoint: 301,
        shaftFlex: "Very Stiff",
        weight: ["3U", "4U"],
        tension: [29, 28],
        style: ["Powerful Attack"],
        imgPath: '../assets/racket-img/astrox-88d-pro-2024.webp',
    },
    {
        id: 2,
        name: "Astrox 88S Pro",
        price: 264.99,
        length: 670,
        balancePoint: 298,
        shaftFlex: "Very Stiff",
        weight: ["3U", "4U"],
        tension: [29, 28],
        style: ["Fast Counter-Attack", "Defend"],
        imgPath: '../assets/racket-img/astrox-88s-pro-2024.webp',
    },
    {
        id: 3,
        name: "Astrox 6",
        price: 149.99,
        "length": 673,
        balancePoint: 295,
        shaftFlex: "Flex",
        weight: ["4U"],
        tension: [26],
        style: ["Attack", "Fast Counter-Attack"],
        imgPath: '../assets/racket-img/astrox-6.JPG',
    },
];